# -*- coding: utf-8 -*-
"""ATS-score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlF6RWTwm4WkDr4m4na0kpXcIc-bZXgk
"""

!pip -q install "sentence-transformers[train]"

import pandas as pd
import numpy as np
import zipfile
import os

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from sentence_transformers import CrossEncoder, InputExample
from sentence_transformers import SentenceTransformer, util
import torch

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

zip_path = "/content/minipro.zip"
extract_path = "/content/data"
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Top files after extract:", os.listdir(extract_path))

import pandas as pd

csv_path = "/content/data/resume_data.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.replace('\ufeff', '', regex=False).str.strip()

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

for i, col in enumerate(df.columns):
    print(i, ":", col)

keywords = ["job", "skill", "respons", "degree", "major", "education", "experience", "match", "score", "company"]
for col in df.columns:
    low = col.lower()
    if any(k in low for k in keywords):
        print(col)

import re
import numpy as np
import pandas as pd

def clean_text(x):
    if pd.isna(x):
        return ""
    x = str(x).lower()
    x = re.sub(r'[^a-z0-9+#./\-\s]', ' ', x)
    x = re.sub(r'\s+', ' ', x).strip()
    return x

df.columns = df.columns.str.replace('\ufeff', '', regex=False).str.strip()

resume_cols = [
    'skills',
    'educational_institution_name',
    'degree_names',
    'educational_results',
    'major_field_of_studies',
    'professional_company_names',
    'company_urls',
    'related_skils_in_job',
    'responsibilities',
    'certification_skills'
]

jd_cols = [
    'job_position_name',
    'educationaL_requirements',
    'experiencere_requirement',
    'responsibilities.1',
    'skills_required'
]

df['resume_text'] = df[resume_cols].apply(lambda row: ' '.join([clean_text(x) for x in row]), axis=1)
df['jd_text'] = df[jd_cols].apply(lambda row: ' '.join([clean_text(x) for x in row]), axis=1)

df['label'] = (df['matched_score'].astype(float) >= 0.5).astype(int)

df = df[
    (df['resume_text'].str.strip() != '') &
    (df['jd_text'].str.strip() != '')
].copy()

df['resume_len'] = df['resume_text'].str.len()
df['jd_len'] = df['jd_text'].str.len()

df = df[(df['resume_len'] > 30) & (df['jd_len'] > 15)].copy()

df = df[['resume_text', 'jd_text', 'label']].drop_duplicates().reset_index(drop=True)

print("Final shape:", df.shape)
print(df['label'].value_counts())
df.head()

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    random_state=42,
    stratify=df['label']
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df['label']
)

print("Train:", train_df.shape)
print("Val:", val_df.shape)
print("Test:", test_df.shape)

print("\nTrain labels:\n", train_df['label'].value_counts())
print("\nVal labels:\n", val_df['label'].value_counts())
print("\nTest labels:\n", test_df['label'].value_counts())

train_counts = train_df['label'].value_counts()
max_count = train_counts.max()

balanced_parts = []
for cls, grp in train_df.groupby('label'):
    balanced_parts.append(grp.sample(max_count, replace=True, random_state=42))

train_df = pd.concat(balanced_parts).sample(frac=1, random_state=42).reset_index(drop=True)

print(train_df['label'].value_counts())
print(train_df.shape)

from sentence_transformers import CrossEncoder, InputExample
from torch.utils.data import DataLoader
import torch

train_examples = [
    InputExample(texts=[row['resume_text'], row['jd_text']], label=float(row['label']))
    for _, row in train_df.iterrows()
]

train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=8)

model = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L6-v2",
    num_labels=1,
    max_length=256,
    activation_fn=torch.nn.Sigmoid()
)

print("Training examples:", len(train_examples))
print("Model loaded with max_length=256 and batch_size=8")

train_small_0 = train_df[train_df['label'] == 0].sample(1000, random_state=42)
train_small_1 = train_df[train_df['label'] == 1].sample(1000, random_state=42)

train_small_df = pd.concat([train_small_0, train_small_1]).sample(frac=1, random_state=42).reset_index(drop=True)

print(train_small_df['label'].value_counts())
print(train_small_df.shape)

train_examples = [
    InputExample(texts=[row['resume_text'], row['jd_text']], label=float(row['label']))
    for _, row in train_small_df.iterrows()
]

train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=8)

print("Training examples:", len(train_examples))

epochs = 2
warmup_steps = max(1, int(len(train_dataloader) * epochs * 0.1))

model.fit(
    train_dataloader=train_dataloader,
    epochs=epochs,
    warmup_steps=warmup_steps,
    show_progress_bar=True
)

from sklearn.metrics import accuracy_score, f1_score
import numpy as np

def predict_scores(model, df_part, batch_size=64):
    pairs = list(zip(df_part['resume_text'].tolist(), df_part['jd_text'].tolist()))
    scores = model.predict(pairs, batch_size=batch_size, show_progress_bar=True)
    return np.array(scores).reshape(-1)

val_scores = predict_scores(model, val_df)

best_acc = 0
best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.30, 0.91, 0.01):
    preds = (val_scores >= t).astype(int)
    acc = accuracy_score(val_df['label'], preds)
    f1 = f1_score(val_df['label'], preds)

    if (acc > best_acc) or (acc == best_acc and f1 > best_f1):
        best_acc = acc
        best_f1 = f1
        best_thresh = float(t)

print("Best Threshold:", best_thresh)
print("Best Validation Accuracy:", round(best_acc, 4))
print("Best Validation F1:", round(best_f1, 4))

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

test_scores = predict_scores(model, test_df)
test_preds = (test_scores >= best_thresh).astype(int)

test_acc = accuracy_score(test_df['label'], test_preds)
test_f1 = f1_score(test_df['label'], test_preds)

print("Final Test Accuracy:", round(test_acc, 4))
print("Final Test F1 Score:", round(test_f1, 4))
print("\nClassification Report:\n")
print(classification_report(test_df['label'], test_preds))
print("Confusion Matrix:\n", confusion_matrix(test_df['label'], test_preds))

train_scores = predict_scores(model, train_small_df)
train_preds = (train_scores >= best_thresh).astype(int)

train_acc = accuracy_score(train_small_df['label'], train_preds)

print("Training Accuracy:", round(train_acc, 4))

def rank_resumes(job_description, resumes, top_k=5):
    pairs = [(r, job_description) for r in resumes]
    scores = model.predict(pairs, batch_size=64, show_progress_bar=False)

    ranked = sorted(zip(resumes, scores), key=lambda x: x[1], reverse=True)
    return [(i + 1, round(float(score), 4), resume) for i, (resume, score) in enumerate(ranked[:top_k])]

sample_jd = test_df['jd_text'].iloc[0]
sample_resumes = test_df['resume_text'].tolist()[:5]

ranked_results = rank_resumes(sample_jd, sample_resumes, top_k=5)

for rank, score, _ in ranked_results:
    print(f"Rank {rank}: Score = {score}")

import re
from sentence_transformers import SentenceTransformer, util

# load model once
model = SentenceTransformer('all-mpnet-base-v2')

def extract_skills(text):
    skill_keywords = [
        'python', 'java', 'c++', 'ml', 'machine learning', 'deep learning',
        'sql', 'aws', 'docker', 'kubernetes', 'nlp', 'data science',
        'tensorflow', 'pytorch', 'flask', 'django', 'html', 'css', 'javascript'
    ]

    text = str(text).lower()
    found_skills = []

    for skill in skill_keywords:
        if re.search(r'\b' + re.escape(skill) + r'\b', text):
            found_skills.append(skill)

    return list(set(found_skills))


def ats_evaluate(resume, jd):
    resume_skills = extract_skills(resume)
    jd_skills = extract_skills(jd)

    matched = list(set(resume_skills) & set(jd_skills))
    missing = list(set(jd_skills) - set(resume_skills))

    if len(jd_skills) == 0:
        score = 0
    else:
        score = (len(matched) / len(jd_skills)) * 100

    return {
        "ATS Score (%)": round(score, 2),
        "Matched Skills": matched,
        "Missing Skills": missing
    }

def hybrid_score(resume, jd):
    sim_score = float(model.predict([(resume, jd)])[0]) * 100
    ats = ats_evaluate(resume, jd)

    return {
        "Semantic Score (%)": round(sim_score, 2),
        **ats
    }

# Example input
resume_input = """
Python SQL ML data analysis Flask HTML CSS
"""

jd_input = """
Looking for candidate with Python SQL ML Docker AWS
"""

# ATS report
result = ats_evaluate(resume_input, jd_input)

print("\n===== ATS REPORT =====")
print(f"ATS Score (%): {result['ATS Score (%)']}")
print(f"Matched Skills: {result['Matched Skills']}")
print(f"Missing Skills: {result['Missing Skills']}")

# Hybrid report
result = hybrid_score(resume_input, jd_input)

print("\n===== HYBRID REPORT =====")
print(f"Semantic Score (%): {result['Semantic Score (%)']}")
print(f"ATS Score (%): {result['ATS Score (%)']}")
print(f"Matched Skills: {result['Matched Skills']}")
print(f"Missing Skills: {result['Missing Skills']}")